force-app/main/default/objects/LoginLocation__c/LoginLocation__c.object-meta.xml
<CustomObject>
    <label>Login Location</label>
    <nameField>
        <displayFormat>LL-{000000}</displayFormat>
        <label>Login Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Login Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LoginLocation__c/fields/IPAddress__c.field-meta.xml
<CustomField>
    <fullName>IPAddress__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IP Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LoginLocation__c/fields/LoginTime__c.field-meta.xml
<CustomField>
    <fullName>LoginTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Login Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LoginLocation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LoginLocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StoreLoginLocation.cls
public with sharing class StoreLoginLocation {

    @InvocableMethod(label='Store Login Info')
    public static void storeLoginInfo(List<LoginEventWrapper> loginEvents) {
        List<LoginLocation__c> loginRecords = new List<LoginLocation__c>();
        System.debug('Storing login information for ' + loginEvents.size() + ' events.');


        for (LoginEventWrapper e : loginEvents) {
            loginRecords.add(new LoginLocation__c(
                User__c = e.UserId,
                IPAddress__c = e.SourceIp,
                City__c = e.LoginGeoCity,
                Country__c = e.LoginGeoCountry,
                LoginTime__c = e.LoginTime
            ));
        }

        if (!loginRecords.isEmpty()) {
            database.insert(loginRecords, false);
            System.debug('Inserted ' + loginRecords.size() + ' login records.');
        }
    }

    public class LoginEventWrapper {
        @InvocableVariable(label='User Id')
        public Id UserId;

        @InvocableVariable(label='Source IP')
        public String SourceIp;

        @InvocableVariable(label='City')
        public String LoginGeoCity;

        @InvocableVariable(label='Country')
        public String LoginGeoCountry;

        @InvocableVariable(label='Login Time')
        public Datetime LoginTime;
    }
}